version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3100:3100"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3200/api/v1

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3200:3200"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/monthlysavings
      - SPRING_DATASOURCE_USERNAME_FILE=/run/secrets/db_user
      - SPRING_DATASOURCE_PASSWORD_FILE=/run/secrets/db_password
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - db
      - redis
    secrets:
      - db_user
      - db_password
    restart: always

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: monthlysavings
      POSTGRES_USER: msuser
      POSTGRES_PASSWORD: mspassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "3500:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3400:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt

volumes:
  pgdata:
  portainer_data:
