services:
  # 1. The Spring Boot Backend Service
  - type: web
    name: family-finance-backend
    runtime: java
    plan: free
    rootDir: ./backend
    buildCommand: "./gradlew bootJar"
    startCommand: "java -Dserver.port=10000 -jar build/libs/*.jar"
    healthCheckPath: /actuator/health
    envVars:
      # Render provides a single DATABASE_URL that Spring Boot automatically detects
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: family-finance-db
          property: connectionString
      - key: SPRING_REDIS_HOST
        fromService:
          type: redis
          name: family-finance-cache
          property: host
      - key: SPRING_REDIS_PORT
        fromService:
          type: redis
          name: family-finance-cache
          property: port

  # 2. The React Frontend Static Site
  - type: static
    name: family-finance-frontend
    plan: free
    rootDir: ./
    buildCommand: "npm install && npm run build"
    publishPath: ./dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: family-finance-backend
          property: url

  # 3. The PostgreSQL Database
  - type: pserv
    name: family-finance-db
    plan: free

  # 4. The Redis Cache
  - type: redis
    name: family-finance-cache
    plan: free
    ipAllowList: [] # Allows access from your other Render services