services:
  # The Spring Boot Backend Service
  - type: web
    name: family-finance-backend
    runtime: java
    plan: free
    rootDir: ./backend
    buildCommand: "./gradlew bootJar"
    startCommand: "java -jar build/libs/*.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromService:
          type: pserv
          name: family-finance-db
          property: connectionString
      - key: SPRING_REDIS_HOST
        fromService:
          type: redis
          name: family-finance-cache
          property: host
      - key: SPRING_REDIS_PORT
        fromService:
          type: redis
          name: family-finance-cache
          property: port
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  # The React Frontend Static Site
  # Static sites are a 'web' service with a 'staticPublishPath'
  - type: web
    name: family-finance-frontend
    runtime: static # Use the 'static' runtime
    plan: free
    rootDir: ./
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./dist
    # This section is crucial for client-side routing in React
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: family-finance-backend
          property: url

  # The PostgreSQL Database
  - type: pserv
    name: family-finance-db
    plan: free

  # The Redis Cache
  - type: redis
    name: family-finance-cache
    plan: free
    # Allow all Render services to connect to this Redis instance
    ipAllowList: []